### ISSUE TITLE
Solution about channel location files

### ISSUE THREAD

**Issue by yellow006** [MeetXinZhang/EEG-ConvTransformer#2]
I have send a copy of the 3D location flie about HydroCel GSN 128 channels. Please check your e-mail.
[GSN-HydroCel-128.xlsx](https://github.com/MeetXinZhang/EEG-ConvTransformer/files/11460145/GSN-HydroCel-128.xlsx)

**Comment by meetxinzhang** [comment]
Thanks for your help, l will update the file and codes soon.



发件人: yellow006 ***@***.***>
发送时间: 2023年5月12日 14:42
收件人: MeetXinZhang/EEG-ConvTransformer ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MeetXinZhang/EEG-ConvTransformer] Something about channel location files (Issue #2)


I have send a copy of the 3D location flie about HydroCel GSN 128 channels. Please check your e-mail.

**Comment by meetxinzhang** [comment]
Hi, @yellow006 , this file has been considered for the projection in AEP. Thanks for your help! Have a nice weekend.
