### ISSUE TITLE
是否复现了论文结果

### ISSUE THREAD

**Issue by busiqiao** [MeetXinZhang/EEG-ConvTransformer#3]
你好，我想问一下这个代码你复现出了论文中说的准确率了吗，我也跑了这个代码但是没有复现出论文中的结果。

**Comment by BryantDom** [comment]
locs = None
TypeError: 'NoneType' object is not iterable
Hi~Brother!Could you solve this problem?

**Comment by busiqiao** [comment]
I solved some problems, but the results still didn't work as in the paper, you can take a look at my folk.在 2023年12月13日，17:15，BryantDom ***@***.***> 写道：﻿
locs = None
TypeError: 'NoneType' object is not iterable
Hi~Brother!Could you solve this problem?
